-- Database: CROCHET
-- Create database if not exists
CREATE DATABASE IF NOT EXISTS CROCHET;
USE CROCHET;

-- Table: USERLIST
-- For storing user information
CREATE TABLE IF NOT EXISTS USERLIST (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_PHONE VARCHAR(20),
    USER_LOCATION VARCHAR(255),
    USER_ADDRESS TEXT,
    USER_ROLE INT DEFAULT 0 COMMENT '0 = Customer, 1 = Admin',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: CATEGORYLIST
-- For storing product categories
CREATE TABLE IF NOT EXISTS CATEGORYLIST (
    CAT_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAT_NAME VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: PRODUCTLIST
-- For storing products
CREATE TABLE IF NOT EXISTS PRODUCTLIST (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NAME VARCHAR(200) NOT NULL,
    PRO_PRICE DECIMAL(10,2) NOT NULL,
    PRO_DETAIL TEXT,
    PRO_IMAGE VARCHAR(255),
    CAT_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CAT_ID) REFERENCES CATEGORYLIST(CAT_ID) ON DELETE SET NULL
);

-- Table: ORDERLIST
-- For storing order information
CREATE TABLE IF NOT EXISTS ORDERLIST (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    PRODUCT_QTY INT NOT NULL DEFAULT 1,
    TOTAL DECIMAL(10,2) NOT NULL,
    ORDER_STATUS VARCHAR(50) DEFAULT 'Pending' COMMENT 'Pending, Processing, Completed, Cancelled',
    DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERLIST(USER_ID) ON DELETE SET NULL
);

-- Table: CUSTOMORDERLIST
-- For storing custom order requests
CREATE TABLE IF NOT EXISTS CUSTOMORDERLIST (
    CUSTOM_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    CUSTOM_PRODUCT_NAME VARCHAR(200) NOT NULL,
    CUSTOM_DETAIL TEXT,
    CUSTOM_PRICE DECIMAL(10,2),
    CUSTOM_STATUS VARCHAR(50) DEFAULT 'Pending',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERLIST(USER_ID) ON DELETE SET NULL
);

-- Table: CONTACTME
-- For storing contact messages
CREATE TABLE IF NOT EXISTS CONTACTME (
    MSG_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    MSG_NAME VARCHAR(100) NOT NULL,
    MSG_EMAIL VARCHAR(100) NOT NULL,
    MSG_PHONE VARCHAR(20),
    MSG_SUBJECT VARCHAR(200),
    MSG_CONTENT TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERLIST(USER_ID) ON DELETE SET NULL
);

-- Table: BALANCELIST (for wallet/balance)
-- For storing user balance information
CREATE TABLE IF NOT EXISTS BALANCELIST (
    BALANCE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    BALANCE_AMOUNT DECIMAL(10,2) DEFAULT 0,
    TRANSACTION_TYPE VARCHAR(20) COMMENT 'Add, Deduct',
    TRANSACTION_DETAIL VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERLIST(USER_ID) ON DELETE CASCADE
);

-- Table: BALANCE (for inventory balance tracking)
-- For storing product inventory balance information
CREATE TABLE IF NOT EXISTS BALANCE (
    BAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROID INT NOT NULL,
    DATET DATETIME DEFAULT CURRENT_TIMESTAMP,
    INCOMEQTY INT DEFAULT 0,
    BALANCE INT DEFAULT 0,
    SALEQTY INT DEFAULT 0,
    FOREIGN KEY (PROID) REFERENCES PRODUCTLIST(PRODUCT_ID) ON DELETE CASCADE
);
